<div style="background-color:#f8f8f8; padding:20px; border:solid 1px #f2f2f2 ">

    <h1 style="font-size:23px; font-weight:bold; margin-bottom:20px">50 Đề Minh họa Luyện thi THPT Quốc gia 2020 môn Toán học</h1>
    <div class="row">
        <div class="col-xs-4 col-sm-4 col-md-4 col-lg-3">
            <a class="thumbnail" href="#" data-image-id="1" data-toggle="modal" data-title="50 Đề Minh họa Luyện thi THPT Quốc gia 2020 môn Toán học" data-image="https://moon.vn/BaiGiangVideo/Image/1847-1.png" data-target="#image-gallery">
                <img id="myImg" width="100%" src="https://moon.vn/BaiGiangVideo/Image/1847-1.png" class="responsive" style="width:100%; border:solid 1px #f2f2f2; " alt="50 Đề Minh họa Luyện thi THPT Quốc gia 2020 môn Toán học" title="50 Đề Minh họa Luyện thi THPT Quốc gia 2020 môn Toán học">
            </a>
        </div>
        <div class="col-xs-8 col-sm-8 col-md-8 col-lg-9">
            <p>ID: [1500] </p>
            <p>Tác giả: <strong>  </strong></p>
            <p class="hidden-sm hidden-xs ">Số Trang:<strong> </strong></p>
            <p class="hidden-sm hidden-xs ">Kích thước:<strong>  19x27cm</strong></p>
            <p class="hidden-sm hidden-xs ">Số lần tra cứu:<strong> Không giới hạn </strong> </p>
            <p>Giá: <strong style="color:red"> 95.000đ</strong> <span style="text-decoration:line-through;padding-left:10px"> 150.000đ</span></p>

            <p style="padding-top:10px;"> <a class="btn btn-danger" style="height:32px"  href="{{ route('cart.add',1) }}"><span class="glyphicon glyphicon-shopping-cart"></span> Mua sách</a> </p>
        </div></div>
    <div style="font-size:13px">
        <p></p><div align="justify"><b>50 ĐỀ MINH HỌA <a href="/sach-id-mon/sach-id-tu-sach-luyen-thi-dai-hoc-mon-toan-hoc">LUYỆN THI THPT QUỐC GIA 2020 MÔN TOÁN HỌC</a></b> được đội ngũ giáo viên của Moon.vn xây dựng, biên soạn và phát triển. Với kho tàng trắc nghiệm hiện nay, việc soạn thảo một đề thi Toán THPT QG là không mấy khó khăn, thế nhưng về mặt tiêu chí chất lượng thì không phải đề nào cũng đáp ứng được. Sự ra đời của cuốn sách <b>50 ĐỀ LUYỆN THI THỬ THPT QUỐC GIA 2020 MÔN TOÁN HỌC</b> giải quyết vấn đề đó.</div><div style="text-align: center;"> <b><a href="https://www.youtube.com/watch?v=bmyeqyCDV4Q&amp;feature=youtu.be" target="_blank" rel="noopener">Xem cách kích hoạt và tra mã ID tại đây!</a></b><br><p><b><a href="https://drive.google.com/file/d/11q2zw44JD52K85LUkz8vSbre_HEHM4PB/view" target="_blank" rel="noopener">Xem bản đọc thử&nbsp;tại đây!</a></b></p></div><p></p>
        <a id="readmoreContentID" data-toggle="collapse" href="#" data-target="#demoContent"> + Xem thêm</a>
        <div id="demoContent" class="collapse">
            <h2><span style="font-size: 14pt;"><b>Đề luyện thi thử THPT QG môn Toán 2020</b> này được viết thành hai phần.</span></h2><div style="text-align: justify; "><b>Phần 1.</b> Các đề Toán, gồm 5 đề thi của Bộ (3 đề thi chính thức, 2 đề thi tham khảo) và 45 đề thi được nhóm tác giả xây dựng.&nbsp;</div><div><b>Phần 2. </b>Đáp án 45 đề thi thử môn Toán THPT QG 2020.&nbsp;</div><div><br></div><div style="text-align: justify; ">Việc tra lời giải chi tiết từng câu trong mỗi đề thi trở lên dễ dàng hơn bao giờ hết, mỗi câu sẽ có một ID riêng, các em chỉ cần nhập ID đó vào ô Tìm ID trên trang chủ moon.vn và Enter là lập tức trang sẽ hiện ra lời giải chi tiết câu đó.</div><div style="text-align: justify; "><br><div align="center"><img src="/Upload/Users1/nguyenthihuyenanhsu/%E1%BA%A2nh%20s%C3%A1ch%20ID/%C4%90%E1%BB%81-thi-th%E1%BB%AD-m%C3%B4n-To%C3%A1n-THPT-QG-2020---7.jpg" alt="Đề-thi-thử-môn-Toán-THPT-QG-2020---7.jpg" width="80%" height="80%" border="0"><br></div><div align="center"><br></div>&nbsp;</div><div style="text-align: justify; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Với <b>50 đề thi thử THPT QG môn Toán 2020 </b>cực kỳ thuyết phục, sách không những đảm bảo tính chất lượng mà còn gây phấn khích về mặt số lượng. 5 đề thi của Bộ, nhóm tác giả đã giải rất tỉ mỉ, cẩn thận, dễ hiểu, tư duy một cách rất tự nhiên để các em nắm bắt kiến thức cũng như ý tưởng của bài toán một cách tốt nhất. 45 đề tiếp đó, các bài toán trong mỗi đề được biên soạn một cách chuẩn mực, phù hợp với kỳ thi THPT Quốc gia. <br></div><div style="text-align: justify; ">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Cuốn sách phủ rộng kiến thức, diệt các dạng toán, đặc biệt các dạng toán thường xuất hiện trong các đề thi của Bộ cũng như các đề thi thử trên toàn quốc. Bên cạnh đó là sự sáng tạo, phát triển, nâng tầm các bài toán và cũng không thể thiếu những bài toán lần đầu tiên xuất hiện tại Việt Nam với những ý tưởng cực kỳ độc đáo.</div><div style="text-align: justify; "><br></div><div align="center"><img src="/Upload/Users1/nguyenthihuyenanhsu/%E1%BA%A2nh%20s%C3%A1ch%20ID/%C4%90%E1%BB%81-thi-th%E1%BB%AD-m%C3%B4n-To%C3%A1n-THPT-QG-2020--11.jpg" alt="Đề-thi-thử-môn-Toán-THPT-QG-2020--11.jpg" title="Đề thi thử môn Toán THPT QG 2020" width="80%" height="80%" border="0">&nbsp;</div><div style="text-align: justify; "><br></div><div style="text-align: justify; ">Thực sự <b>50 ĐỀ MINH HỌA THI THỬ THPT QUỐC GIA 2020 MÔN TOÁN HỌC</b> là một cuốn sách chất lượng, đáng tin cậy dành cho các em. Cuốn sách là sự nỗ lực, rất tâm huyết của nhóm tác giả, mong muốn, hy vọng các em có được bộ đề Toán chất lượng, ôn luyện chuẩn bị cho kỳ THPT Quốc gia sắp tới. Bên cạnh đó, nhóm tác giả xin được gửi lời cảm ơn đến tập thể phòng Nội dung Moon.vn đã nỗ lực ngày đêm, viết Latex trên trang chủ moon.vn, tạo ID … để các em thi online trên trang một cách tốt nhất.</div><div style="text-align: justify; "><br></div>
            <div align="center"><img src="/Upload/Users1/nguyenthihuyenanhsu/%E1%BA%A2nh%20s%C3%A1ch%20ID/%C4%90%E1%BB%81-thi-th%E1%BB%AD-m%C3%B4n-To%C3%A1n-THPT-QG-2020-2.jpg" alt="Đề-thi-thử-môn-Toán-THPT-QG-2020-2.jpg" title="Đề thi thử THPT QG 2020 môn Toán" width="80%" height="80%" border="0"></div><div align="center"><br></div><div align="center"><img src="/Upload/Users1/nguyenthihuyenanhsu/%E1%BA%A2nh%20s%C3%A1ch%20ID/%C4%90%E1%BB%81-thi-th%E1%BB%AD-m%C3%B4n-To%C3%A1n-THPT-QG-2020---4.jpg" alt="Đề-thi-thử-môn-Toán-THPT-QG-2020---4.jpg" title="50 Đề thi thử môn Toán THPT QG 2020" width="80%" height="80%" border="0"></div><div align="center">Thầy Nguyễn Thế Duy - Một trong 3 tác giả của 50 đề minh họa thi thử THPT QG 2020
            </div></div> </div>
</div>
