@extends('layouts.landing')
@section('content-top')
    @include('static-block.content-top')
@endsection
@section('content')
    @include("landing-page.introduction.partials.scholarship")
@endsection
@section('content-bottom')
    @include('static-block.content-bottom')
@endsection
